name: lighthouse

on: [push]

jobs:
  generate_lighthouse_audit:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Audit preview URL with Lighthouse
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://cats.purduesolutions.org/
            https://cats-git-dev-purduesolutions.vercel.app/
          uploadArtifacts: true
          temporaryPublicStorage: true