name: Cypress Tests

on: [push]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"